services:
  python-3-13:
    image: python:3.13-slim-bookworm
    network_mode: host
    env_file:
      - .env
    command: ["sleep", "infinity"]
    volumes:
      - ../..:/workspaces:cached
    ports:
      - 3000:3000
