openapi: 3.0.3
info:
  title: Rawe Ceek API
  version: 1.0.0
servers:
  - url: https://raweceek.eu/api
tags:
  - name: Event
  - name: System
paths:
  /events:
    get:
      tags:
        - Event
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventDto"
  /events/next:
    get:
      tags:
        - Event
      responses:
        '200':
          description: Next event by startTime
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/EventDto"
  /system/health:
    get:
      tags:
        - System
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
        default:
          description: Service is not healthy
components:
  schemas:
    EventDto:
      type: object
      properties:
        summary:
          type: string
          example: üèÅ FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX 2024 - Race
        location:
          type: string
          example: United Arab Emirates
        startTime:
          type: string
          example: 2024-12-08T13:00Z
      required:
        - token
        - expires
