additionalProperties:
  modelPackage: eu.raweceek.codegen.models
  apiPackage: eu.raweceek.codegen.api
  interfaceOnly: true
  skipDefaultInterface: true
  groupId: eu.raweceek
  artifactId: codegen
  artifactVersion: 1.0.0
  openApiNullable: false
  useSpringBoot3: true
  hideGenerationTimestamp: true
